_core:
  default_config_hash: BIZhfTth9kW1JD4jc2oTmO7mKyFnt2sK4DjKtuzsfzY
admin_css: true
responsive_image: true
one_pixel: true
blazy:
  loadInvisible: false
  offset: 100
  saveViewportOffsetDelay: 50
  validateDelay: null
