_core:
  default_config_hash: GkrROi2gto34V7Z_ZFN2bCV1HzzLw0WAFHhIdloceog
attributes:
  class:
    label: ''
    description: ''
  target:
    label: ''
    description: ''
    options:
      _blank: 'New window (_blank)'
      _self: 'Same window (_self)'
  container_class:
    label: 'List-item classes'
    description: 'Classes added to the parent list-item element'
